version: "3.9"

services:
  application:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
# docker compose up --build - using docker compose

